#!/bin/bash

SWITCH="\e["
NORMAL="${SWITCH}0m"
YELLOW="${SWITCH}33m"
RED="${SWITCH}31m"
GREEN="${SWITCH}32m"
BLUE="${SWITCH}34m"

dir=$(dirname "${BASH_SOURCE[0]}")
file="$1"
dest=http://localhost:8889/gm

host=http://localhost:8890
url=$host/gm
# ?file="$file"\&post_url="$dest"
echo $url

auth='Basic dGVzdDp0ZXN0MTIz'

curl -G -v -H "x-auth: $auth" "$url" --data-urlencode "file=$file" --data-urlencode "post_url=$dest"

